### ISSUE TITLE
Asset Compute custom worker - outdated content

### ISSUE THREAD

**Issue by pawee-del** [AdobeDocs/asset-compute.en#4]
Issue in ./help/setup-environment.md

this is outdated, no longer have firefly template

**Comment by bohnertchris** [comment]
Thanks for the issue, @pawee-del. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Closing, this was resolved.
