### ISSUE TITLE
issue when registering in app builder

### ISSUE THREAD

**Issue by pawee-del** [AdobeDocs/asset-compute.en#5]
Hi do you know who do i contact if my app builder throws an error during register?

 (node:43038) UnhandledPromiseRejectionWarning: Error: Unable to invoke /register: 403 {"error_code":"403025", "message":"Profile is not valid"}

**Comment by aheim0** [comment]
This is outside the scope of the documentation. 

We suggest that you contact Support, see the following for more information:
- https://experienceleague.adobe.com/?support-solution=Experience+Manager&lang=en#support
